In [1]:
import tensorflow as tf
import numpy as np

In [13]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None,2], dtype=tf.float32),))
def test_signature(W):
    print("trace avec W.shape:",W.shape)
    return W*2

In [14]:
test_signature(tf.ones([2,2]))

trace avec W.shape: (None, 2)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [15]:
test_signature(tf.zeros([2,2]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [16]:
test_signature(tf.ones([3,2]))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)>

In [17]:
test_signature(tf.ones([3,3]))

ValueError: ignored